# Generated by Django 5.2 on 2025-07-15 22:42

import app.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.TextField()),
                ('adress', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField()),
                ('log_type', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_email', models.CharField(max_length=100)),
                ('sender_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('message_date', models.DateTimeField()),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransmissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.status')),
            ],
        ),
        migrations.CreateModel(
            name='SoldVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('license_plate', models.CharField(max_length=50)),
                ('mileage', models.DecimalField(decimal_places=2, max_digits=18)),
                ('color', models.CharField(max_length=50)),
                ('seats', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('power', models.DecimalField(decimal_places=2, max_digits=18)),
                ('engine_size', models.DecimalField(decimal_places=2, max_digits=18)),
                ('body_style', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.bodystyle')),
                ('fuel_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.fueltype')),
                ('transmission_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.transmissiontype')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicledata'),
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.utils.vehicle_image_upload_path)),
                ('vehicle_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicledata')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleImageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(blank=True, null=True)),
                ('vehicle_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicledata')),
                ('vehicle_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicleimage')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('person', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vehicle')),
            ],
        ),
    ]
